name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  format:

    name: format
    runs-on: ubuntu-latest

    container:
      image: elixir:latest

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: mix format --check-formatted

  unit-test:

    name: unit test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.4' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          priv/plts
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get --only test
    - name: Lint
      run: mix dialyzer
    - name: Run tests
      env:
        MIX_ENV: test
      run: mix do ecto.migrate, test

